version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: pocketid_pocketid_1
      APP_PORT: 1411

  pocketid:
    image: pocketid/pocket-id:v2
    user: "1000:1000"
    init: true
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
